import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import preferArrow from 'eslint-plugin-prefer-arrow-functions';
import unicorn from 'eslint-plugin-unicorn';
import promise from 'eslint-plugin-promise';
import noUnsanitized from 'eslint-plugin-no-unsanitized';
import sonarjs from 'eslint-plugin-sonarjs';
import { recommended, source, test } from '@adobe/eslint-config-helix';
import configDrift from './tools/eslint-rules/config-drift.js';

export default defineConfig([
  globalIgnores([
    '**/vendor',
    // Generated by `npm test -- --coverage` (gitignored, not committed) —
    // third-party istanbul report scripts, not this project's source.
    'coverage/**',
    // adobe/aem-experimentation, vendored via `git subtree` — upstream code,
    // updated with `git subtree pull`, never hand-edited. Linting it would
    // force local edits that the next subtree pull would conflict with.
    'plugins/experimentation/**',
  ]),
  {
    languageOptions: {
      ...recommended.languageOptions,
      ecmaVersion: 2025,
      globals: {
        ...globals.serviceworker,
        ...globals.browser,
        ...globals.mocha,
        ...globals.es6,
        __rootdir: true,
      },
    },
    settings: {
      // 'stylelint': this project's import/resolver (eslint-import-resolver-node)
      // doesn't understand exports-only package.json fields (no `main`), which is
      // all stylelint declares — a real resolver limitation, not an unresolved
      // import. It genuinely resolves and runs fine at runtime (used by
      // tools/stylelint-rules/z-index-requires-token.js and its test).
      'import/core-modules': ['eslint/config', 'stylelint'],
    },
    rules: {
      'no-await-in-loop': 0,

      'object-curly-newline': ['error', {
        multiline: true,
        minProperties: 6,
        consistent: true,
      }],

      'import/no-cycle': 'off',

      'max-statements-per-line': ['error', { max: 2 }],

      'header/header': 0,

      'class-methods-use-this': 0,

      'import/no-unresolved': ['error', {
        ignore: ['^https?://'],
      }],

      // scripts.md: "Utilities should not import from blocks — dependency
      // flows one direction: blocks -> utils." True by convention only until
      // now (an architect-agent audit found zero violations today, but
      // nothing would have caught one) — same rationale as the config-drift
      // rules below: this project already writes enforcement for invariants
      // it cares about rather than leaving them as prose alone.
      'import/no-restricted-paths': ['error', {
        zones: [{
          target: './scripts/utils',
          from: './blocks',
          message: 'scripts/utils/ must not import from blocks/ — dependency flows one direction: blocks -> utils (see .claude/rules/scripts.md).',
        }],
      }],

      indent: ['error', 2, {
        ignoredNodes: ['TemplateLiteral *'],
        SwitchCase: 1,
      }],

      'no-param-reassign': ['error', { props: false }],

      // arrow-only: all function declarations/expressions → arrow functions
      'prefer-arrow-functions/prefer-arrow-functions': ['error', {
        allowNamedFunctions: false,
        classPropertiesAllowed: false,
        disallowPrototype: true,
        returnStyle: 'implicit',
        singleReturnOnly: false,
      }],

      'prefer-arrow-callback': ['error', { allowNamedFunctions: false }],
      'arrow-body-style': ['error', 'as-needed'],
      'func-style': ['error', 'expression'],

      // terse expressions: prefer modern array methods over manual loops
      'no-restricted-syntax': ['error',
        {
          selector: 'ForInStatement',
          message: 'Use Object.keys/values/entries with for...of or array methods.',
        },
      ],

      // no nested ternaries (inherited from Helix, enforced here explicitly)
      'no-nested-ternary': 'error',

      // F-22: reactive/stateful blocks (e.g. pricing) are the one place
      // vanilla JS with no build step has real correctness risk with no
      // compiler backstop — cap cyclomatic complexity as a lint-time signal
      // instead of leaving it to review alone. Was present but disabled (0);
      // this just turns on the max Helix already suggested.
      complexity: ['error', 20],

      // config-drift guard (P0-48): catch a locale-prefix list or an
      // environment/hostname classification re-implemented outside this
      // project's designated single-source files.
      'config-drift/no-duplicate-locale-list': 'error',
      'config-drift/no-inline-env-check': 'error',

      // Hand-picked from eslint-plugin-unicorn, NOT its full `recommended`
      // preset — most of that preset (no-null, no-anonymous-default-export,
      // prevent-abbreviations, no-array-for-each, ...) actively fights this
      // project's own documented conventions (the `export default (el) => {}`
      // block contract is an anonymous default export; `el`/`idx` abbreviations
      // and `.forEach()` one-liners are established style per linting.md).
      // These seven don't conflict with anything documented and each directly
      // enforces a convention this project's own style guide already states in
      // prose: array methods over manual loops, modern DOM APIs, ES2025 idioms.
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-array-find': 'error',
      'unicorn/no-for-loop': 'error',
      'unicorn/prefer-query-selector': 'error',
      'unicorn/prefer-modern-dom-apis': 'error',
      'unicorn/prefer-optional-catch-binding': 'error',
      'unicorn/prefer-add-event-listener': 'error',
      // Matches this project's own documented style: "`at(-1)` for
      // last-element access" (CLAUDE.md) — not yet enforced anywhere.
      'unicorn/prefer-array-last-methods': 'error',

      // eslint-plugin-promise's recommended set, minus `param-names` (bikeshed
      // on parameter naming, not a real bug — this project's test files use
      // `res`/`rej`, which is fine). `catch-or-return`/`always-return` catch a
      // real, previously-uncaught bug class: a `.then()` chain (used for
      // fire-and-forget dynamic imports in lazy.js/scripts.js/ak.js) with no
      // `.catch()` produces a silent unhandled rejection if the import or its
      // callback throws.
      'promise/param-names': 'off',

      // Mozilla's eslint-plugin-no-unsanitized (used in production at Mozilla
      // itself) — flags innerHTML/outerHTML/insertAdjacentHTML/document.write
      // assignments and dynamic import() calls that aren't a provably-safe
      // literal. Every real innerHTML site in this codebase was rewritten to
      // build real DOM nodes (scripts/utils/dom.js's parseSvg()) instead of
      // ever assigning to innerHTML at all — not silenced, actually avoided.
      //
      // For dynamic import(), the 2 real non-literal call sites are each
      // wrapped in a small, named, documented function (resolvePreviewOrigin,
      // resolveModulePath) whose contract is "this only
      // ever returns a same-origin/validated string, never arbitrary attacker
      // input" — registered below so the rule trusts their return value
      // instead of needing a disable at every call site. See each function's
      // own doc comment for its specific safety argument.
      'no-unsanitized/property': 'error',
      'no-unsanitized/method': ['error', {
        escape: {
          methods: ['resolvePreviewOrigin', 'resolveModulePath'],
        },
      }],

      // SonarSource's cognitive-complexity (not cyclomatic — weights nesting,
      // which is the more honest proxy for "can a human follow this"). Same
      // F-22 rationale as the `complexity` rule above, measuring a different,
      // complementary thing rather than duplicating it. 15 is sonarjs's own
      // documented default, not an arbitrary pick.
      'sonarjs/cognitive-complexity': ['error', 15],
    },
    plugins: {
      import: recommended.plugins.import,
      'prefer-arrow-functions': preferArrow,
      'config-drift': configDrift,
      unicorn,
      promise,
      'no-unsanitized': noUnsanitized,
      sonarjs,
    },
    extends: [recommended, promise.configs['flat/recommended']],
  },
  source,
  test,
  {
    files: ['test/**/*.js'],
    rules: {
      'max-classes-per-file': 0,
      'no-console': 'off',
      'no-underscore-dangle': 0,
      'no-unused-expressions': 0,
      // no-unsanitized is a real-attacker-vs-real-author-content rule — test
      // fixtures building mock DOM from test-authored HTML strings have no
      // such boundary (it's the test author's own trusted string, not
      // content that ever reaches a real visitor), so it doesn't apply here.
      'no-unsanitized/property': 'off',
      'no-unsanitized/method': 'off',
    },
  },
  {
    // Backstop only, not the block-size rule. The real rule (blocks.md
    // Structure) is concerns-based and enforced in review: one directory per
    // block, `default(el, { signal })` as the only public contract, helpers
    // split into sibling files once a file mixes concerns, shared utils
    // reused first. Line count doesn't measure that, so this cap sits well
    // above today's largest block file (100 counted lines, 2026-09-25) and
    // only catches a file that has plainly grown past one concern without
    // anyone splitting it. It replaced a 100-line cap that pushed files to
    // be compressed to fit rather than split by concern. No file-level
    // disables exist; don't add one, split the file instead.
    files: ['blocks/**/*.js'],
    rules: {
      'max-lines': ['error', { max: 200, skipBlankLines: true, skipComments: true }],
    },
  },
]);
