name = "ak-website"
main = "index.js"
compatibility_date = "2025-02-14"
keep_vars = true

vars = { AEM_ORG = "dallinbsmith", AEM_SITE = "atreyu" }

[env.staging]
vars = { AEM_ORG = "dallinbsmith", AEM_SITE = "atreyu" }

[env.production]
vars = { AEM_ORG = "dallinbsmith", AEM_SITE = "atreyu" }
